version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  prisma:
    container_name: prisma-studio
    build:
      context: .
    env_file:
      - .env
    expose:
      - "5555"
    ports:
      - ${PRISMA_STUDIO_PORT}:5555
    links:
      - postgres
    depends_on:
      - postgres

  server:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data:
  server-data: